# Generated by Django 6.0.2 on 2026-03-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(null=True)),
                ('name', models.TextField()),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('mob_no', models.BigIntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('title', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tbl_employee',
            },
        ),
    ]
