# Generated by Django 6.0.2 on 2026-03-15 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_user', to='crudapp.empdetail')),
            ],
            options={
                'db_table': 'tbl_log_emp',
            },
        ),
    ]
