# Generated by Django 6.0.2 on 2026-03-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_loggedinuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdetail',
            name='date',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
