# Generated by Django 6.0.2 on 2026-03-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_empdetail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetail',
            name='mob_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
