# Generated by Django 6.0.2 on 2026-03-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_alter_empdetail_mob_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetail',
            name='mob_no',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
