# Generated by Django 6.0.2 on 2026-03-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0005_alter_empdetail_mob_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetail',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
